# Generated by Django 4.2.2 on 2023-06-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'verbose_name_plural': 'Move'},
        ),
    ]
